# Zombi
zombi.name=Zombi
zombi.symbol=Z
zombi.color=GREEN
zombi.maxHealth=100
zombi.health=100
zombi.agality=25
zombi.strength=50
zombi.hostility=LOW

# VAMPIRE
vampire.name=Zampire
vampire.symbol=V
vampire.color=RED
vampire.maxHealth=100
vampire.health=100
vampire.agality=100
vampire.strength=50
vampire.hostility=HIGH

# GROST
grost.name=Grost
grost.symbol=G
grost.color=WHITE
grost.maxHealth=25
grost.health=25
grost.agality=100
grost.strength=25
grost.hostility=LOW

# ORGE
orge.name=Orge
orge.symbol=O
orge.color=YELLOW
orge.maxHealth=100
orge.health=100
orge.agality=25
orge.strength=100
orge.hostility=MEDIUM

# SNAKE_MAGE
snake_mage.name=Snake_mage
snake_mage.symbol= S
snake_mage.color=WHITE
snake_mage.maxHealth=50
snake_mage.health=50
snake_mage.agality=100
snake_mage.strength=50
snake_mage.hostility=HIGH