# Zombi
zombi.name=Zombi
zombi.symbol=Z
zombi.color=GREEN
zombi.maxHealth=100
zombi.health=100
zombi.agility=50
zombi.strength=30
zombi.hostility=2

# VAMPIRE
vampire.name=Zampire
vampire.symbol=V
vampire.color=RED
vampire.maxHealth=100
vampire.health=100
vampire.agility=90
vampire.strength=30
vampire.hostility=6

# GROST
grost.name=Grost
grost.symbol=G
grost.color=WHITE
grost.maxHealth=25
grost.health=25
grost.agility=90
grost.strength=70
grost.hostility=2

# ORGE
orge.name=Orge
orge.symbol=O
orge.color=YELLOW
orge.maxHealth=100
orge.health=100
orge.agility=25
orge.strength=50
orge.hostility=4

# SNAKE_MAGE
snake_mage.name=Snake_mage
snake_mage.symbol= S
snake_mage.color=WHITE
snake_mage.maxHealth=50
snake_mage.health=50
snake_mage.agility=100
snake_mage.strength=50
snake_mage.hostility=6