# Zombie
zombie.name=Zombie
zombie.symbol=Z
zombie.color=GREEN
zombie.maxHealth=100
zombie.health=100
zombie.agility=50
zombie.strength=30
zombie.hostility=2

# VAMPIRE
vampire.name=Vampire
vampire.symbol=V
vampire.color=RED
vampire.maxHealth=100
vampire.health=100
vampire.agility=90
vampire.strength=30
vampire.hostility=6

# GHOST
ghost.name=Ghost
ghost.symbol=G
ghost.color=WHITE
ghost.maxHealth=25
ghost.health=25
ghost.agility=90
ghost.strength=70
ghost.hostility=2

# Ogre
ogre.name=Ogre
ogre.symbol=O
ogre.color=YELLOW
ogre.maxHealth=100
ogre.health=100
ogre.agility=100
ogre.strength=50
ogre.hostility=4

# SNAKE_MAGE
snake_mage.name=Snake_mage
snake_mage.symbol= S
snake_mage.color=WHITE
snake_mage.maxHealth=50
snake_mage.health=50
snake_mage.agility=100
snake_mage.strength=50
snake_mage.hostility=6